from .base import BaseIndicator
from .cpi import CPIIndicator
from .social_finance import SocialFinanceIndicator
from .margin import MarginIndicator
from .forex import ForexIndicator
from .commodity import CommodityIndicator
from .sox import SOXIndicator
from .shibor import ShiborIndicator
from .bond import BondIndicator
from .gdp import GDPIndicator
from .ppi import PPIIndicator
from .pmi import PMIIndicator
from .m2 import M2Indicator
from .sugar import SugarIndicator
from .commodity_index import CommodityIndexIndicator
from .energy_index import EnergyIndexIndicator
from .pig import PigIndicator
from .oil import OilIndicator
from .lpr import LPRIndicator
from .international_rate import InternationalRateIndicator
from .insurance import InsuranceIndicator
from .nev_sale import NEVSaleIndicator
from .real_estate import RealEstateIndicator
from .trade import TradeIndicator
from .news_cloud import NewsIndicator
from .scissors_gap import ScissorsGapIndicator
from .electricity import ElectricityIndicator
from .city_real_estate import MunicipalRealEstateIndicator
from .macro_digest import MacroDigestIndicator
from .stock_shareholder import StockShareholderIndicator
from .erp import ERPIndicator
from .market_leverage import MarketLeverageIndicator
from .buffett_indicator import BuffettIndicator
from .keqiang_index import KeqiangIndicator
from .liquidity_portrait import LiquidityPortraitIndicator
from .m1_m2_gap import M1M2GapIndicator
from .market_pe import MarketPEIndicator
from .cross_border import CrossBorderIndicator
from .real_yield import RealInterestRateIndicator
