from .base import BaseIndicator
from .cpi import CPIIndicator
from .social_finance import SocialFinanceIndicator
from .margin import MarginIndicator
from .forex import ForexIndicator
from .commodity import CommodityIndicator
from .sox import SOXIndicator
from .shibor import ShiborIndicator
from .bond import BondIndicator
from .gdp import GDPIndicator
from .ppi import PPIIndicator
from .pmi import PMIIndicator
from .m2 import M2Indicator
from .sugar import SugarIndicator
from .commodity_index import CommodityIndexIndicator
from .energy_index import EnergyIndexIndicator
from .pig import PigIndicator
from .oil import OilIndicator
from .lpr import LPRIndicator
from .international_rate import InternationalRateIndicator
from .insurance import InsuranceIndicator
