"""Publish one JSON snapshot to a registered shared-KV module; no read/list."""
import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from core.shared_data_client import MAX_UPLOAD_BYTES, SharedDataClient, SharedDataError


def load_payload(file):
    try:
        with Path(file).open('rb') as stream:
            raw = stream.read(MAX_UPLOAD_BYTES + 1)
    except OSError:
        raise SharedDataError('payload_file_unavailable') from None
    if len(raw) > MAX_UPLOAD_BYTES:
        raise SharedDataError('payload_too_large')

    def reject_non_finite(_value):
        raise ValueError()

    try:
        payload = json.loads(raw.decode('utf-8'), parse_constant=reject_non_finite)
    except (ValueError, UnicodeError, RecursionError):
        raise SharedDataError('invalid_payload_file') from None
    if not isinstance(payload, (dict, list)) or not payload:
        raise SharedDataError('empty_payload')
    return payload


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--module', required=True, help='Registered module, for example academic:metrics')
    parser.add_argument('--file', required=True, help='UTF-8 JSON payload generated by the producer')
    args = parser.parse_args(argv)
    stage = 'payload_validation'
    try:
        if not re.fullmatch(r'[a-z0-9][a-z0-9_-]*:[a-z0-9][a-z0-9_-]*', args.module):
            raise SharedDataError('invalid_module')
        payload = load_payload(args.file)
        stage = 'configuration'
        client = SharedDataClient()
        stage = 'snapshot_upload'
        # Metadata is taken from the caller's GitHub environment, not the
        # checked-out toolkit repository. No post-upload read/list in production.
        client.upload(args.module, payload)
        print(f'Uploaded snapshot for {args.module}.', flush=True)
        return 0
    except SharedDataError as error:
        print(f'Failed stage: {stage}', file=sys.stderr)
        print(str(error), file=sys.stderr)
        if error.worker_code == 'unknown_module':
            print('Register the module with its own key and caller repository before publishing; preserve all existing registry entries.', file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
