name: "Module: ETF Monitor"

on:
  # schedule:
  #   # 02:00 UTC = 10:00 CST
  #   - cron: '30 1 * * 1-5'
  #   # 03:35 UTC = 11:35 CST (Morning Close)
  #   - cron: '35 2 * * 1-5'
  #   # 06:30 UTC = 14:30 CST
  #   - cron: '30 5 * * 1-5'
  #   # 07:05 UTC = 15:05 CST (Market Close)
  #   - cron: '5 6 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load workflow .env
        uses: ./.github/actions/load-dotenv
        with:
          env_text: ${{ secrets.PUSH_ENV_FILE }}
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run ETF
        run: python main.py run etf --topic stock
