name: "Module: Stock Market"

on:
  # schedule:
  #   # 03:30 UTC = 11:30 CST
  #   - cron: '30 2 * * 1-5'
  #   # 07:00 UTC = 15:00 CST
  #   - cron: '0 6 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load workflow .env
        uses: ./.github/actions/load-dotenv
        with:
          env_text: ${{ secrets.PUSH_ENV_FILE }}
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Stock/ETF
        run: python main.py run stock --topic stock
